### ISSUE TITLE
Application crash if you scroll to edge of map

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#155]
From the debug menu I un-ticked limit edge and got this crash as I zoomed out to search for someone

Faulting application name: CorsixTH_DirectX.exe, version: 0.0.0.0, time stamp: 0x514780f0
Faulting module name: CorsixTH_DirectX.exe, version: 0.0.0.0, time stamp: 0x514780f0
Exception code: 0xc0000005
Fault offset: 0x0002dff9
Faulting process id: 0x684
Faulting application start time: 0x01cf16dcde18a337
Faulting application path: C:\Users\Mark\Desktop\corsixth\CorsixTH-experimental-epidemics\CorsixTH\CorsixTH_DirectX.exe
Faulting module path: C:\Users\Mark\Desktop\corsixth\CorsixTH-experimental-epidemics\CorsixTH\CorsixTH_DirectX.exe
Report Id: 1c819e90-82d3-11e3-8e9e-8c89a5160b8f

As you will see from the report it was with DX

**Comment by pwaller** [comment]
I believe I've hit this running master c09f5a0. It's not reproducible easily.

It occurred after going to the save menu with the mouse, and whilst the save dialog is open the map scrolled up until the game crashed. I took a screenshot from the moment of the crash, and I observe that it is not possible with a fresh load of the game to scroll up as far as the view captured in the screenshot (even with some trying).

I managed to capture this stack trace.

```
#0  0x0000000000436956 in THLinkList::getDrawingLayer (this=0xff929e71ff8e9675)
    at /home/pwaller/th/CorsixTH/Src/th.h:37
No locals.
#1  0x0000000000443864 in THMap::draw (this=0x406f8778, pCanvas=0x400212d8, 
    iScreenX=-505, iScreenY=340, iWidth=1182, iHeight=664, iCanvasX=0, 
    iCanvasY=0) at /home/pwaller/th/CorsixTH/Src/th_map.cpp:892
        bTileNeedsRedraw = false
        bNeedsRedraw = false
        iBlock = 0
        pItem = 0xff929e71ff8e9675
        iH = 0
        bRedrawAnimations = true
        itrNode = {m_pNode = 0x8b50c48, m_pNodeFirst = 0x8b7fe58, 
          m_pNodeEnd = 0x8b4e498, m_iNodeStep = -127, m_iXStep = 64, 
          m_iXs = 1145, m_iYs = -20, m_takenSteps = 19}
        bPreviousTileNeedsRedraw = false
        itrNode2 = {static ms_iMarginTop = 150, static ms_iMarginLeft = 110, 
          static ms_iMarginRight = 110, static ms_iMarginBottom = 150, 
          m_pNode = 0x8b50c48, m_pMap = 0x406f8778, m_iXs = 1145, m_iYs = -20, 
          m_iScreenX = -505, m_iScreenY = 340, m_iScreenWidth = 1182, 
          m_iScreenHeight = 664, m_iBaseX = 0, m_iBaseY = 20, m_iX = 20, 
          m_iY = 0, m_iScanlineCount = 20, m_eDirection = ScanlineForward}
        rcClip = {<SDL_Rect> = {x = 0, y = 0, w = 1182, 
            h = 664}, <No data fields>}
        bFirst = false
        formerIterator = {m_pNode = 0x8b4e448, m_pNodeFirst = 0x40080000, 
          m_pNodeEnd = 0x8b4e448, m_iNodeStep = -127, m_iXStep = 64, 
          m_iXs = 1177, m_iYs = -36, m_takenSteps = 20}
#2  0x0000000000471284 in l_map_draw (L=0x41517898)
    at /home/pwaller/th/CorsixTH/Src/th_lua_map.cpp:769
        pMap = 0x406f8778
        pCanvas = 0x400212d8
#3  0x00007ffff7651a9b in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#4  0x000000000042e6db in l_mainloop (L=0x40000378)
    at /home/pwaller/th/CorsixTH/Src/sdl_core.cpp:286
        do_frame = true
        do_timer = true
        fps_control = 0x40047b08
        timer = 1
        e = {type = 32768, common = {type = 32768, timestamp = 5632356}, 
          window = {type = 32768, timestamp = 5632356, windowID = 0, 
            event = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', 
            padding3 = 0 '\000', data1 = 5632326, data2 = 0}, key = {
            type = 32768, timestamp = 5632356, windowID = 0, state = 0 '\000', 
            repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', 
            keysym = {scancode = 5632326, sym = 0, mod = 45997, 
              unused = 32767}}, edit = {type = 32768, timestamp = 5632356, 
            windowID = 0, 
            text = "\000\000\000\000F\361U\000\000\000\000\000\255\263\340\364\377\177\000\000\024D\315T\000\000\000\000\025\240\271", <incomplete sequence \367>, start = 32767, length = 5764}, text = {type = 32768, timestamp = 5632356, 
            windowID = 0, 
            text = "\000\000\000\000F\361U\000\000\000\000\000\255\263\340\364\377\177\000\000\024D\315T\000\000\000\000\025\240\271", <incomplete sequence \367>}, motion = {type = 32768, timestamp = 5632356, windowID = 0, which = 0, 
            state = 5632326, x = 0, y = -186600531, xrel = 32767, 
            yrel = 1422738452}, button = {type = 32768, timestamp = 5632356, 
            windowID = 0, which = 0, button = 70 'F', state = 241 '\361', 
            clicks = 85 'U', padding1 = 0 '\000', x = 0, y = -186600531}, 
          wheel = {type = 32768, timestamp = 5632356, windowID = 0, which = 0, 
            x = 5632326, y = 0}, jaxis = {type = 32768, timestamp = 5632356, 
            which = 0, axis = 0 '\000', padding1 = 0 '\000', 
            padding2 = 0 '\000', padding3 = 0 '\000', value = -3770, 
            padding4 = 85}, jball = {type = 32768, timestamp = 5632356, 
            which = 0, ball = 0 '\000', padding1 = 0 '\000', 
            padding2 = 0 '\000', padding3 = 0 '\000', xrel = -3770, 
            yrel = 85}, jhat = {type = 32768, timestamp = 5632356, which = 0, 
            hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', 
            padding2 = 0 '\000'}, jbutton = {type = 32768, 
            timestamp = 5632356, which = 0, button = 0 '\000', 
            state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, 
          jdevice = {type = 32768, timestamp = 5632356, which = 0}, caxis = {
            type = 32768, timestamp = 5632356, which = 0, axis = 0 '\000', 
            padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', 
            value = -3770, padding4 = 85}, cbutton = {type = 32768, 
            timestamp = 5632356, which = 0, button = 0 '\000', 
            state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, 
          cdevice = {type = 32768, timestamp = 5632356, which = 0}, quit = {
            type = 32768, timestamp = 5632356}, user = {type = 32768, 
            timestamp = 5632356, windowID = 0, code = 0, data1 = 0x55f146, 
            data2 = 0x7ffff4e0b3ad <__GI___clock_gettime+29>}, syswm = {
            type = 32768, timestamp = 5632356, msg = 0x0}, tfinger = {
            type = 32768, timestamp = 5632356, touchId = 0, 
            fingerId = 5632326, x = -1.42421723e+32, y = 4.59163468e-41, 
            dx = 7.05288366e+12, dy = 0, pressure = -7.52985756e+33}, 
          mgesture = {type = 32768, timestamp = 5632356, touchId = 0, 
            dTheta = 7.89256977e-39, dDist = 0, x = -1.42421723e+32, 
            y = 4.59163468e-41, numFingers = 17428, padding = 21709}, 
          dgesture = {type = 32768, timestamp = 5632356, touchId = 0, 
            gestureId = 5632326, numFingers = 4108366765, 
            error = 4.59163468e-41, x = 7.05288366e+12, y = 0}, drop = {
            type = 32768, timestamp = 5632356, file = 0x0}, 
          padding = "\000\200\000\000d\361U\000\000\000\000\000\000\000\000\000F\361U\000\000\000\000\000\255\263\340\364\377\177\000\000\024D\315T\000\000\000\000\025\240\271\367\377\177\000\000\204\026\000\000\000\000\000"}
        dispatcher = 0x41517898
        n = 4373264
#5  0x00007ffff7651a9b in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#6  0x000000000045219f in CorsixTH_lua_main (L=0x40000378)
    at /home/pwaller/th/CorsixTH/Src/main.cpp:192
No locals.
#7  0x00007ffff7651a9b in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#8  0x00007ffff7694d00 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#9  0x000000000042bd5a in main (argc=1, argv=0x7fffffffe028)
    at /home/pwaller/th/CorsixTH/SrcUnshared/main.cpp:85
        L = 0x40000378
        stkCleanup = {
          c = {<std::_Deque_base<void (*)(), std::allocator<void (*)()> >> = {
              _M_impl = {<std::allocator<void (*)()>> = {<__gnu_cxx::new_allocator<void (*)()>> = {<No data fields>}, <No data fields>}, 
                _M_map = 0x7fffffffdeb0, _M_map_size = 4639604, _M_start = {
                  _M_cur = 0x6a8a48, _M_first = 0x46e13a
     <std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >::~map()>, _M_last = 0x6a8a48, 
                  _M_node = 0x7ffff4d3e3c9 <__cxa_atexit+25>}, _M_finish = {
                  _M_cur = 0x2, _M_first = 0x7fffffffdef0, _M_last = 0x6a7d30, 
                  _M_node = 0x46c7a4 <__static_initialization_and_destruction_0(int, int)+59>}}}, <No data fields>}}
        bRun = true
```

**Comment by TheCycoONE** [comment]
Does not appear to be an issue with SDL2.

**Comment by TheCycoONE** [comment]
I believe this still does happen in 0.50 but it's a duplicate of #124
