### ISSUE TITLE
[Bug] Segfault on exit with SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1869]
#### Describe the issue
Every time I stop corsix-th it freezes for several minutes and then segfaults. The location of the segfault is not consistent. I've seen very similar bugs with other SDL2 software on this machine before, which might be related, e.g.: https://github.com/dosbox-staging/dosbox-staging/issues/336 It does not segfault without SDL_VIDEODRIVER (i.e. in x11 mode)

#### Steps to Reproduce
1. Run SDL_VIDEODRIVER=wayland ./corsix-th
2. Click exit

#### Expected Behavior
Clean shutdown

#### System Information
**CorsixTH Version:** 

**Operating System:** Arch Linux, using sway-wm 1.6

**Theme Hospital Version:** CD

### Additional Info
```
#0  0x0000ffff917c86a0 in ?? ()
(gdb) bt
#0  0x0000ffff917c86a0 in  ()
#1  0x0000ffff9c6b5218 in  () at /usr/lib/libSDL2-2.0.so.0
#2  0x0000ffff9c6ade24 in  () at /usr/lib/libSDL2-2.0.so.0
#3  0x0000aaaaaf96b9b0 in raw_bitmap::~raw_bitmap()
    (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/stephen/corsixth/CorsixTH/Src/th_gfx_sdl.cpp:714
#4  0x0000aaaaaf948430 in luaT_stdgc<raw_bitmap, -1001001>(lua_State*) (L=<optimized out>)
    at /home/stephen/corsixth/CorsixTH/Src/th_lua.h:380
#5  0x0000ffff9c5cedf4 in luaD_call
    (L=0xaaaad5912e18, func=0xaaaaded65960, nresults=0) at ldo.c:481
#6  0x0000ffff9c5cf0ec in luaD_callnoyield
    (L=0xaaaad5912e18, func=0xaaaaded65960, nResults=0) at ldo.c:525
#7  0x0000ffff9c5d388c in dothecall (L=0xaaaad5912e18, ud=0x0)
    at lgc.c:889
#8  0x0000ffff9c5cdd68 in luaD_rawrunprotected
    (L=0xaaaad5912e18, f=0xffff9c5d3860 <dothecall>, ud=0x0)
    at ldo.c:148
#9  0x0000ffff9c5cfab0 in luaD_pcall
    (L=0xaaaad5912e18, func=0xffff9c5d3860 <dothecall>, u=0x0, old_top=48, ef=0) at ldo.c:749
#10 0x0000ffff9c5d3a10 in GCTM (L=0xaaaad5912e18) at lgc.c:909
#11 0x0000ffff9c5d3b24 in callallpendingfinalizers (L=0xaaaad5912e18)
    at lgc.c:939
#12 0x0000ffff9c5d4cf4 in luaC_freeallobjects (L=0xaaaad5912e18)
    at lgc.c:1502
#13 0x0000ffff9c5dc1bc in close_state (L=0xaaaad5912e18)
    at lstate.c:311
#14 0x0000ffff9c5dc844 in lua_close (L=0xaaaad5912e18)
    at lstate.c:444
#15 0x0000aaaaaf939d04 in cleanup (L=0xaaaad5912e18)
    at /home/stephen/corsixth/CorsixTH/SrcUnshared/main.cpp:59
#16 main(int, char**) (argc=1, argv=0xffffd25f8698)
    at /home/stephen/corsixth/CorsixTH/SrcUnshared/main.cpp:122
```

```
#0  0x0000ffff83fbf6a0 in ?? ()
(gdb) bt
#0  0x0000ffff83fbf6a0 in  ()
#1  0x0000ffff92ed7218 in  () at /usr/lib/libSDL2-2.0.so.0
#2  0x0000ffff92ecfe24 in  () at /usr/lib/libSDL2-2.0.so.0
#3  0x0000aaaabd1dbba4 in sprite_sheet::_freeSingleSprite(unsigned long) (this=this@entry=0xaaaac70985c8, iNumber=iNumber@entry=357)
    at /home/stephen/corsixth/CorsixTH/Src/th_gfx_sdl.cpp:837
#4  0x0000aaaabd1dbc20 in sprite_sheet::_freeSprites()
    (this=0xaaaac70985c8)
    at /home/stephen/corsixth/CorsixTH/Src/th_gfx_sdl.cpp:851
#5  0x0000aaaabd1dbc5c in sprite_sheet::~sprite_sheet()
    (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/stephen/corsixth/CorsixTH/Src/th_gfx_sdl.cpp:831
#6  0x0000aaaabd1b8494 in luaT_stdgc<sprite_sheet, -1001001>(lua_State*) (L=<optimized out>)
    at /home/stephen/corsixth/CorsixTH/Src/th_lua.h:380
#7  0x0000ffff92df0df4 in luaD_call
    (L=0xaaaabe0d6e18, func=0xaaaac7531350, nresults=0) at ldo.c:481
#8  0x0000ffff92df10ec in luaD_callnoyield
    (L=0xaaaabe0d6e18, func=0xaaaac7531350, nResults=0) at ldo.c:525
#9  0x0000ffff92df588c in dothecall (L=0xaaaabe0d6e18, ud=0x0)
    at lgc.c:889
#10 0x0000ffff92defd68 in luaD_rawrunprotected
    (L=0xaaaabe0d6e18, f=0xffff92df5860 <dothecall>, ud=0x0)
    at ldo.c:148
#11 0x0000ffff92df1ab0 in luaD_pcall
    (L=0xaaaabe0d6e18, func=0xffff92df5860 <dothecall>, u=0x0, old_top=48, ef=0) at ldo.c:749
#12 0x0000ffff92df5a10 in GCTM (L=0xaaaabe0d6e18) at lgc.c:909
#13 0x0000ffff92df5b24 in callallpendingfinalizers (L=0xaaaabe0d6e18)
    at lgc.c:939
#14 0x0000ffff92df6cf4 in luaC_freeallobjects (L=0xaaaabe0d6e18)
    at lgc.c:1502
#15 0x0000ffff92dfe1bc in close_state (L=0xaaaabe0d6e18)
    at lstate.c:311
#16 0x0000ffff92dfe844 in lua_close (L=0xaaaabe0d6e18)
    at lstate.c:444
#17 0x0000aaaabd1a9d04 in cleanup (L=0xaaaabe0d6e18)
    at /home/stephen/corsixth/CorsixTH/SrcUnshared/main.cpp:59
#18 main(int, char**) (argc=1, argv=0xffffe46a9cd8) at /home/stephen/corsixth/CorsixTH/SrcUnshared/main.cpp:122
```

**Comment by lewri** [comment]
Any hints on direction to fix from your referenced issue? Looks like there was a lot of tasty information in it. Also do you have a priority for this (or is it definitely upstream?).

**Comment by TheCycoONE** [comment]
Assuming it's the same as the dosbox staging bug linked, then it is upstream (mesa graphics driver bug) but it's been there for many years now and we'll want to implement a workaround like they did, controlling the order that things are destroyed in.
