### ISSUE TITLE
[Bug] Game crash after selecting Folders menu in Czech

### ISSUE THREAD

**Issue by kparal** [CorsixTH/CorsixTH#1902]
Forking this from #1901 .

#### Steps to Reproduce
1. Select font to be able to display Czech translation (I used Dejavu Sans)
2. Pick Czech translation (čeština )
3. Go to Folders menu ("Složky")
4. Game crashes:
```
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FT_Vector_; _Alloc = std::allocator<FT_Vector_>; std::vector<_Tp, _Alloc>::reference = FT_Vector_&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
```

#### System Information
**CorsixTH Version:** 0.65-beta1, from Flathub

**Operating System:** Fedora 34

**Theme Hospital Version:** GOG

#### Gamelog.txt
No gamelog, probably because I haven't started the game yet.

**Comment by lewri** [comment]
Confirmed in Windows

**Comment by lewri** [comment]
It also crashed with Russian? (Pyncchi?)

**Comment by TheCycoONE** [comment]
Can reproduce (with noto mono):
```
==2084==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xffff38c07536 at pc 0xaaaae8c65120 bp 0xffffeb82ee60 sp 0xffffeb82ee78
READ of size 1 at 0xffff38c07536 thread T0
    #0 0xaaaae8c6511c in freetype_font::draw_text_wrapped(render_target*, char const*, unsigned long, int, int, int, int, int, text_alignment) const /home/stephen/corsixth/build-clang/../CorsixTH/Src/th_gfx_font.cpp:574:11
    #1 0xaaaae8c64208 in freetype_font::get_text_dimensions(char const*, unsigned long, int) const /home/stephen/corsixth/build-clang/../CorsixTH/Src/th_gfx_font.cpp:468:10
    #2 0xaaaae8bb1c54 in (anonymous namespace)::l_font_draw(lua_State*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/th_lua_gfx.cpp:347:34
    #3 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #4 0xffff8d013450  (/usr/lib/liblua.so.5.4+0x21450)
    #5 0xffff8d0025ac  (/usr/lib/liblua.so.5.4+0x105ac)
    #6 0xffff8d001ca0  (/usr/lib/liblua.so.5.4+0xfca0)
    #7 0xffff8d002cf0 in lua_resume (/usr/lib/liblua.so.5.4+0x10cf0)
    #8 0xaaaae8ba4420 in luaT_resume(lua_State*, lua_State*, int, int*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/th_lua.h:129:10
    #9 0xaaaae8ba36f8 in (anonymous namespace)::l_mainloop(lua_State*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/sdl_core.cpp:287:13
    #10 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #11 0xffff8d0134b0  (/usr/lib/liblua.so.5.4+0x214b0)
    #12 0xffff8d002c48  (/usr/lib/liblua.so.5.4+0x10c48)
    #13 0xffff8cffc22c in lua_callk (/usr/lib/liblua.so.5.4+0xa22c)
    #14 0xaaaae8b91b9c in lua_main(lua_State*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/main.cpp:116:3
    #15 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #16 0xffff8d002c30  (/usr/lib/liblua.so.5.4+0x10c30)
    #17 0xffff8d001ca0  (/usr/lib/liblua.so.5.4+0xfca0)
    #18 0xffff8d002fe4  (/usr/lib/liblua.so.5.4+0x10fe4)
    #19 0xffff8cffc318 in lua_pcallk (/usr/lib/liblua.so.5.4+0xa318)
    #20 0xaaaae8b920f8 in main /home/stephen/corsixth/build-clang/../CorsixTH/SrcUnshared/main.cpp:102:9
    #21 0xffff8b351534 in __libc_start_main (/usr/lib/libc.so.6+0x24534)
    #22 0xaaaae8ab0a20 in _start (/home/stephen/corsixth/build-clang/CorsixTH/corsix-th+0x50a20)

0xffff38c07536 is located 0 bytes to the right of 70-byte region [0xffff38c074f0,0xffff38c07536)
allocated by thread T0 here:
    #0 0xaaaae8b55d9c in realloc (/home/stephen/corsixth/build-clang/CorsixTH/corsix-th+0xf5d9c)
    #1 0xffff8d008934  (/usr/lib/liblua.so.5.4+0x16934)
    #2 0xffff8d00614c  (/usr/lib/liblua.so.5.4+0x1414c)
    #3 0xffff8d00ed60  (/usr/lib/liblua.so.5.4+0x1cd60)
    #4 0xffff8cffb198 in lua_pushlstring (/usr/lib/liblua.so.5.4+0x9198)
    #5 0xffff8d02498c  (/usr/lib/liblua.so.5.4+0x3298c)
    #6 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #7 0xffff8d0134b0  (/usr/lib/liblua.so.5.4+0x214b0)
    #8 0xffff8d0025ac  (/usr/lib/liblua.so.5.4+0x105ac)
    #9 0xffff8d001ca0  (/usr/lib/liblua.so.5.4+0xfca0)
    #10 0xffff8d002cf0 in lua_resume (/usr/lib/liblua.so.5.4+0x10cf0)
    #11 0xaaaae8ba4420 in luaT_resume(lua_State*, lua_State*, int, int*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/th_lua.h:129:10
    #12 0xaaaae8ba36f8 in (anonymous namespace)::l_mainloop(lua_State*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/sdl_core.cpp:287:13
    #13 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #14 0xffff8d0134b0  (/usr/lib/liblua.so.5.4+0x214b0)
    #15 0xffff8d002c48  (/usr/lib/liblua.so.5.4+0x10c48)
    #16 0xffff8cffc22c in lua_callk (/usr/lib/liblua.so.5.4+0xa22c)
    #17 0xaaaae8b91b9c in lua_main(lua_State*) /home/stephen/corsixth/build-clang/../CorsixTH/Src/main.cpp:116:3
    #18 0xffff8d00293c  (/usr/lib/liblua.so.5.4+0x1093c)
    #19 0xffff8d002c30  (/usr/lib/liblua.so.5.4+0x10c30)
    #20 0xffff8d001ca0  (/usr/lib/liblua.so.5.4+0xfca0)
    #21 0xffff8d002fe4  (/usr/lib/liblua.so.5.4+0x10fe4)
    #22 0xffff8cffc318 in lua_pcallk (/usr/lib/liblua.so.5.4+0xa318)
    #23 0xaaaae8b920f8 in main /home/stephen/corsixth/build-clang/../CorsixTH/SrcUnshared/main.cpp:102:9
    #24 0xffff8b351534 in __libc_start_main (/usr/lib/libc.so.6+0x24534)
    #25 0xaaaae8ab0a20 in _start (/home/stephen/corsixth/build-clang/CorsixTH/corsix-th+0x50a20)
```
